### ISSUE TITLE
Refuse to connect if user click on "View" button of the Problem blank xblock

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/wg-build-test-release#480]
https://github.com/openedx/frontend-app-authoring/issues/1895

**Comment by tonybusa** [comment]
@mariajgrimaldi @PKulkoRaccoonGang - I'm looking into this issue and was wondering if there is a specific test case that this bug is related to on the spreadsheet that I can reference for recreating the behavior?

Thanks!

**Comment by mariajgrimaldi** [comment]
@tonybusa: Thanks for picking this up! I'm not aware of a test case for this. @crathbun428: Do you think there should be a test case that detects this kind of failure?

**Comment by tonybusa** [comment]
I was able to recreate the issue! I'll document the steps here in a minute for anyone who wants to test the fix later.

**Comment by crathbun428** [comment]
> [@tonybusa](https://github.com/tonybusa): Thanks for picking this up! I'm not aware of a test case for this. [@crathbun428](https://github.com/crathbun428): Do you think there should be a test case that detects this kind of failure?

I'll add one.

**Comment by jmakowski1123** [comment]
Apologies, I missed writing this test.

The expected behavior should be:

When a user clicks "view", they should see a page with all of the problems contained in the problem bank. Users can scroll through the problems.

<img width="1357" alt="Image" src="https://github.com/user-attachments/assets/ac4f5d17-2950-49be-9476-3576b614a9de" />

When a user clicks the large "edit" button in the right header, the modal to configure the problem bank opens.

<img width="1365" alt="Image" src="https://github.com/user-attachments/assets/7d6d572e-7d23-4b1d-8a21-5536f0c9c906" />

When a user clicks on "edit" in any particular problem, the editor for that particular problem opens.

<img width="1348" alt="Image" src="https://github.com/user-attachments/assets/469c518f-3c2d-4f2f-9839-d62ea7b4ba85" />

**Comment by tonybusa** [comment]
Thanks for clarifying @jmakowski1123. I made some comments on the linked ticket: https://github.com/openedx/frontend-app-authoring/issues/1895 - sorry if I should be keeping them on this parent ticket. But seeing your test cases this has given me some other questions.

**The view link:**
1. Which link do we want to display:
- /container - seems to display the legacy code that allows full functionality (doesnt render within iframe, incorrect headers)
- /container_embed - seems to display some updated code, but the editing buttons are broken (more on that later)

2. Should the view link do the following:
- route to another full page to see the content of the components
- open a new tab to show the full content of the components
- render within an iframe (current behavior) which is truncated by the limited size of the iframe (see comment in linked story with screenshots)

**The edit button:**

- If we render the /container path then we can use the full edit functionality as you showed in your screenshot. Or this example also shows:

![Image](https://github.com/user-attachments/assets/d27876b2-feb1-46f8-af04-bf1f796447da)

- If we render the /container_embed path (which works renders within the iframe using the correct headers), we see 2 edit buttons, both of which don't work:

![Image](https://github.com/user-attachments/assets/1079580f-6e47-4f26-8006-b3838741bcf1)

**Comment by jmakowski1123** [comment]
Thanks @tonybusa . I'll try to answer these as best I can from product, but also tagging @bradenmacdonald who implemented the [original story. ](https://github.com/openedx/frontend-app-authoring/issues/1385)

When I test this in our Sumac sandbox, this is the link that displays: https://studio.sumac.openedx.io/container/block-v1:e0dX+assessment_0001+2025_01+type@itembank+block@6391bf7a1b7546dcaac7f4257127be4c

It should not open in a new tab. I'm not sure, though, if it should be implemented as an iframe.

**Comment by tonybusa** [comment]
@jmakowski1123  it appears to me that the Sumac sandbox is routing from the Django frontend of Problem Bank to the Django frontend of "view" for the Problem Bank. The Teak sandbox seems to want to go from the Authoring MFE frontend of Problem Bank to the Django frontend of "view" for the Problem Bank. This is why there's an iFrame currently.

**Comment by bradenmacdonald** [comment]
@tonybusa CC @jmakowski1123 @PKulkoRaccoonGang 

Here is the expected behavior, for both **Legacy Randomized Content** blocks (`library_content` in URL/ID) and the newer **Problem Bank** (`itembank` in URL/ID)

## Normal view in Authoring MFE Unit page:

![Image](https://github.com/user-attachments/assets/c3bbc619-42c5-4920-a320-0d7368d50e02)

Clicking any **View** link  (there are three in the screenshot above) may _temporarily_ redirect to the legacy CMS URL (i.e. `http://studio.local.openedx.io:8001/container/...`) but should then redirect the user to this page, which shows the `container_embed` view in the Course Authoring MFE, not the legacy UI `/container` page:

e.g. http://apps.local.openedx.io:2001/authoring/course/course-v1:BradenX+CP200+23/container/block-v1:BradenX+CP200+23+type@itembank+block@7715431ac18a4272a479db671253a7da/block-v1:BradenX+CP200+23+type@vertical+block@c66a3d40b8ba401d9b8c0f0a38cfca13

![Image](https://github.com/user-attachments/assets/9db7fb00-e2aa-4d0a-9f77-e5c41a7366c7)

Clicking on any of the edit buttons from that page:
![Image](https://github.com/user-attachments/assets/8170c1b6-affe-4829-9413-021fb5d3a29c)

Should stay in the Authoring MFE and open the component editor in a modal:
![Image](https://github.com/user-attachments/assets/274640ec-3f38-4803-8919-7be11f31a3e9)


The above flow seems to be working on master, although there are a few issues:
- an error about `upstreamLink` missing
    * If you see this, fix it with:  
       ![Image](https://github.com/user-attachments/assets/97579cc1-e870-4f26-b5d9-2e386b8b62e6)
- There are duplicate edit buttons in the UI
    * If you see this, fix it with:  
       ![Image](https://github.com/user-attachments/assets/6dac9d1e-42c9-4d8e-8b77-ee0c5a5856c5)
- The "add components" button isn't working from the `container_embed` page. It can be worked around by adding components from the parent unit page, but this will need to be fixed.
      ![Image](https://github.com/user-attachments/assets/ccde8a54-3488-410c-8d71-d825e8681002)

If you are seeing different behavior, you likely have incorrect waffle flags set.

**Comment by bradenmacdonald** [comment]
> If we render the /container path then we can use the full edit functionality as you showed in your screenshot. Or this example also shows:

You should not be able to access the `/container` path directly; the waffle flags for your instance should be configured to redirect the container path to the MFE.

> If we render the /container_embed path (which works renders within the iframe using the correct headers), we see 2 edit buttons, both of which don't work:

This view isn't meant to be accessed directly. When it's embedded in the iframe, the edit buttons should be working fine.

> render within an iframe (current behavior) which is truncated by the limited size of the iframe (see comment in linked story with screenshots)

That sounds like an unrelated bug. The iframe size is supposed to be dynamically adjusted to fit the contents.

**Comment by tonybusa** [comment]
Thanks for the detailed comments @bradenmacdonald. I pulled the latest master and I still can't recreate the flow. I'm new to WAFFLE FLAGS but I can see how to get to them in the Admin page. Could you tell me which flags I can use to update my studio so that I can get to the same state as you? I think this will likely also close @PKulkoRaccoonGang 's issue if we can both see the functionality as expected.

**Comment by bradenmacdonald** [comment]
@tonybusa 

Oh, my information was slightly out of date. For Teak and master, there is no need to set a waffle flag. The "unit page in MFE" is the default, unless you explicitly create a `legacy_studio.unit_editor` waffle flag and enable it. So I'm really not sure why you're not seeing the same flow. If you're using Tutor you should go to http://studio.local.openedx.io:8001/admin/waffle/flag/ and double check that there is no `legacy_studio.unit_editor` flag present. I checked on https://studio.teak.demo.edly.io/admin/waffle/flag/ and confirmed it's not set.

You can see [here](https://apps.teak.demo.edly.io/authoring/course/course-v1:OpenedX+LCD+1/container/block-v1:OpenedX+LCD+1+type@vertical+block@41680a04994942b4bbccd7c1b653f1ef/block-v1:OpenedX+LCD+1+type@sequential+block@bb1ff3f2d4f9476eba710de88231c513) on the Teak sandbox. That Unit has a Problem Bank. Click "View" and it will redirect you to the legacy /container endpoint which immediately redirects you back to the MFE at [this URL](https://apps.teak.demo.edly.io/authoring/course/course-v1:OpenedX+LCD+1/container/block-v1:OpenedX+LCD+1+type@itembank+block@6754f55afd8a4a69818da306a42d02b0/block-v1:OpenedX+LCD+1+type@vertical+block@41680a04994942b4bbccd7c1b653f1ef) although it's currently not loading because of [this bug](https://github.com/openedx/frontend-app-authoring/issues/2007)

(For Sumac: I forgot that Sumac is still using the legacy unit page. What I said above about the desired flow only applies to Teak and master. But for the record, if you wanted to test it out in Sumac, on a Tutor devstack, you could go to http://studio.local.openedx.io:8001/admin/waffle/flag/ and create a flag with the name `contentstore.new_studio_mfe.use_new_unit_page` set to "Enabled for everyone". But the default is off.)

**Comment by tonybusa** [comment]
@bradenmacdonald thanks again for the sanity check on my local setup that is helpful to know.

Unfortunately, I'm trying the Teak sandbox link: https://apps.teak.demo.edly.io/authoring/course/course-v1:OpenedX+LCD+1/container/block-v1:OpenedX+LCD+1+type@vertical+block@41680a04994942b4bbccd7c1b653f1ef/block-v1:OpenedX+LCD+1+type@sequential+block@bb1ff3f2d4f9476eba710de88231c513 

and I'm still not seeing the same behavior as you have been describing. I clicked on the same course you reference in your URL:
- Openedx LCD - Library Content Usage. But I do notice your URL is different in that it says "itembank+block" rather than mine saying "vertical+block" so I'm wondering why the difference. Here's your URL (https://apps.teak.demo.edly.io/authoring/course/course-v1:OpenedX+LCD+1/container/block-v1:OpenedX+LCD+1+type@itembank+block@6754f55afd8a4a69818da306a42d02b0/block-v1:OpenedX+LCD+1+type@vertical+block@41680a04994942b4bbccd7c1b653f1ef) 

Here's a recording from the Teak sandbox:

https://github.com/user-attachments/assets/7cba763e-cb55-466f-83ac-9f1183a90805

**Comment by bradenmacdonald** [comment]
@tonybusa OK, I see now that there is different behavior depending on which "View" link you click (see below). They _should_ be doing the same thing, but the one on the top right is mostly working correctly (except for the other unrelated bugs I mentioned), and the one on the

![Image](https://github.com/user-attachments/assets/b0026fbf-84f0-4260-95e3-f0c6444c1497)

**One problem** is that the left (red) "View" link is just changing the URL of the iframe. It should be updated to have `target="_top"` so that it changes the URL of the whole page when clicked. When you click it now without `target="_top"`, it only changes the URL within the iframe and Studio's built-in protection to not allow its regular pages to be embedded in iframes kicks in and gives you that error.

A **second problem** is: I was wrong about how this works. It seems that Studio is not actually redirecting back to the MFE. Rather, when you click on the right (green) link, some JavaScript is intercepting it and replacing the destination with the correct MFE URL. I'm not sure off hand where this is happening, but you can confirm that it is because if you right-click and copy the link location then paste it into a new tab, you'll see the legacy page with no redirect back to the MFE. So we either need to update the legacy page to redirect to the MFE, change the click intercept code to handle _both_ view links, change the `itembank` block so that its View link is recognized and intercepted the same way (is it missing a CSS class?), or remove the broken "View" link and keep only the working one.

**Comment by tonybusa** [comment]
Thanks @bradenmacdonald your suggestion for the ```target="_top"``` fixes the behavior. I've created a PR: https://github.com/openedx/edx-platform/pull/36781
