### ISSUE TITLE
Teams feature is not working

### ISSUE THREAD

**Issue by luisfelipec95** [openedx/wg-build-test-release#502]
### Release

teak

### Expected behavior

The expected behavior is that the teams are created successfully without generating any errors.

### Actual behavior

While testing the Teams functionality, we encountered the following error, when accessing the Teams tab in the LMS and attempting to create a new team under a specific topic, an error is occurring in the interface of this section

### Steps to reproduce

1. Log in to an installation with the SUMAC version installed.
2. Configure the team topic under _Pages & Resources_ > _Teams_. 
3. Go to the Teams tab within the course in the LMS and open the topic you previously created
4. Attempt to create a new team.

### Additional information

![Image](https://github.com/user-attachments/assets/894e7655-73e2-4395-aea6-3eef5ea04a53)

**Comment by Asespinel** [comment]
I think this is already solved in main 

![Image](https://github.com/user-attachments/assets/d8bfc844-1472-484d-8b04-eb4d8e566637)

I have no issues creating a new team and it was already cherry picked here in sumac: https://github.com/openedx/edx-platform/commit/c1804f58765a554fbeeb251cacb1b5c670b54354

**Comment by BryanttV** [comment]
Hi @luisfelipec95, thanks for the report! Please, could you tell me with which user type you tried to create the team?

In my first tests I had the following behavior.

With an **admin** user:
1. I created a Topic from Studio.
2. I created a Team within the Topic from the LMS.

Everything worked without problems (similar to what @Asespinel reports that he also tested with an admin user according to the capture)

Then, with a **student** (from the previously created Topic)
1. I created a Team within the Topic from the LMS

I got the same error **(This discussion could not be loaded. Refresh the page and try again)**. However, the Team was created, but every time I enter the Team I get the same error, and this is true for all other Teams that have been created.

**Comment by Asespinel** [comment]
Hello @BryanttV you were right with a student user we get the same error described above. In my logs I saw the following error:
`lms-1          | 2025-05-20 04:53:49,988 INFO 3167 [tracking] [user 6] [ip 172.19.0.1] logger.py:41 - {"name": "edx.team.page_viewed", "context": {"user_id": 6, "path": "/event", "course_id": "course-v1:OpenedX+DemoX+DemoCourse", "org_id": "OpenedX", "enterprise_uuid": ""}, "username": "user1", "session": "80444e714d5da6e4071cac747c57baf3", "ip": "172.19.0.1", "agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0", "host": "local.openedx.io:8000", "referer": "http://local.openedx.io:8000/courses/course-v1:OpenedX+DemoX+DemoCourse/teams/", "accept_language": "en-US,en;q=0.5", "event": "{\"page_name\": \"single-team\", \"topic_id\": \"social\", \"team_id\": \"test-team-67ae4fe9014842d3af046516ea2cafe0\"}", "time": "2025-05-20T04:53:49.988061+00:00", "event_type": "edx.team.page_viewed", "event_source": "browser", "page": "http://local.openedx.io:8000/courses/course-v1:OpenedX+DemoX+DemoCourse/teams/#teams/social/test-team-67ae4fe9014842d3af046516ea2cafe0"}
lms-1          | ************************************
lms-1          | course-v1:OpenedX+DemoX+DemoCourse
lms-1          | [20/May/2025 04:53:50] "POST /event HTTP/1.1" 200 7
lms-1          | 2025-05-20 04:53:50,067 ERROR 3167 [forum.api.users] [user 6] [ip 172.19.0.1] users.py:36 - Forumv2RequestError for retrieving user's data for id 6.
lms-1          | desde el forum backend**************************************************
lms-1          | None
lms-1          | 2025-05-20 04:53:50,068 ERROR 3167 [root] [user None] [ip None] signals.py:22 - Uncaught exception from None
lms-1          | Traceback (most recent call last):
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/user.py", line 247, in _retrieve
lms-1          |     response = forum_api.get_user(
lms-1          |                ^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/forum/api/users.py", line 37, in get_user
lms-1          |     raise ForumV2RequestError(str(f"user not found with id: {user_id}"))
lms-1          | forum.utils.ForumV2RequestError: user not found with id: 6
lms-1          | 
lms-1          | During handling of the above exception, another exception occurred:
lms-1          | 
lms-1          | Traceback (most recent call last):
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/opaque_keys/__init__.py", line 189, in from_string
lms-1          |     namespace, rest = cls._separate_namespace(serialized)
lms-1          |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/opaque_keys/__init__.py", line 220, in _separate_namespace
lms-1          |     raise InvalidKeyError(cls, serialized)
lms-1          | opaque_keys.InvalidKeyError: <class 'opaque_keys.edx.keys.CourseKey'>: None
lms-1          | 
lms-1          | During handling of the above exception, another exception occurred:
lms-1          | 
lms-1          | Traceback (most recent call last):
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
lms-1          |     response = get_response(request)
lms-1          |                ^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
lms-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
lms-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/opt/pyenv/versions/3.11.8/lib/python3.11/contextlib.py", line 81, in inner
lms-1          |     return func(*args, **kwds)
lms-1          |            ^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
lms-1          |     return view_func(request, *args, **kwargs)
lms-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/edx-platform/lms/djangoapps/discussion/views.py", line 213, in wrapped_view
lms-1          |     return view_func(request, course_key, *args, **kwargs)
lms-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/edx-platform/lms/djangoapps/discussion/views.py", line 228, in inline_discussion
lms-1          |     user_info = cc_user.to_dict(course_key=str(course_key))
lms-1          |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/models.py", line 65, in to_dict
lms-1          |     self.retrieve(course_key=course_key)
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/models.py", line 70, in retrieve
lms-1          |     self._retrieve(*args, **kwargs)
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/user.py", line 254, in _retrieve
lms-1          |     self.save({"course_id": course_id})
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/models.py", line 170, in save
lms-1          |     response = self.handle_update(params)
lms-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/models.py", line 235, in handle_update
lms-1          |     response = self.handle_update_user(request_params, str(course_key))
lms-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/models.py", line 248, in handle_update_user
lms-1          |     response = forum_api.update_user(
lms-1          |                ^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/forum/api/users.py", line 58, in update_user
lms-1          |     backend = get_backend(course_id)()
lms-1          |               ^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/forum/backend.py", line 38, in _get_backend
lms-1          |     if is_mysql_backend_enabled(course_id):
lms-1          |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/forum/backend.py", line 26, in is_mysql_backend_enabled
lms-1          |     course_key = CourseKey.from_string(course_id)
lms-1          |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/opaque_keys/__init__.py", line 198, in from_string
lms-1          |     return cls.deprecated_fallback._from_deprecated_string(serialized)  # type: ignore
lms-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/opaque_keys/edx/locator.py", line 403, in _from_deprecated_string
lms-1          |     raise InvalidKeyError(cls, serialized)
lms-1          | opaque_keys.InvalidKeyError: <class 'opaque_keys.edx.locator.CourseLocator'>: None
lms-1          | Internal Server Error: /courses/course-v1:OpenedX+DemoX+DemoCourse/discussion/forum/67ae4fe9014842d3af046516ea2cafe0/inline
lms-1          | Traceback (most recent call last):
lms-1          |   File "/openedx/edx-platform/openedx/core/djangoapps/django_comment_common/comment_client/user.py", line 247, in _retrieve
lms-1          |     response = forum_api.get_user(
lms-1          |                ^^^^^^^^^^^^^^^^^^^
lms-1          |   File "/openedx/venv/lib/python3.11/site-packages/forum/api/users.py", line 37, in get_user
lms-1          |     raise ForumV2RequestError(str(f"user not found with id: {user_id}"))
lms-1          | forum.utils.ForumV2RequestError: user not found with id: 6
`
It appeared like the student got an error since he isn't found inside the forum db. So what I did was to create a test post inside the discussions and I don't get the error again:

![Image](https://github.com/user-attachments/assets/256d5fb8-8032-4a5e-8a0e-72f723b2adf6)

Do you think thats the expected behaviour? It only seems that the user is being created inside the froum db when they create a post. Should the user be also created when they want to join a team?

**Comment by BryanttV** [comment]
Thanks @Asespinel!. This doesn't seem to be the expected behavior.

**Comment by BryanttV** [comment]
I’ve been reviewing this issue, but I noticed it hasn’t been assigned a test case ID yet. While checking the spreadsheet, I found `TC_LEARNER_47`, already successfully executed.

However, I’m not entirely sure whether this is the correct ID to assign, especially since the reported error (which is still occurring) seems to be related more to Discussions than to Teams.

@mariajgrimaldi @crathbun428, What could we do in this case?

**Comment by BryanttV** [comment]
I’ve been running additional tests based on what @Asespinel reported, and I found that the error is related to a call to the Discussions Forum API, not specifically to Teams.

When a Team is created, the [inline discussions endpoint](https://github.com/openedx/edx-platform/blob/d1854d00200a836fb9f4ba6e8492d147dad1039b/lms/djangoapps/discussion/views.py#L215) is called. The failure occurs specifically at [this line](https://github.com/openedx/edx-platform/blob/d1854d00200a836fb9f4ba6e8492d147dad1039b/lms/djangoapps/discussion/views.py#L222) when it tries to access the user information:

```python
user_info = cc_user.to_dict(course_key=str(course_key))
```
In the `to_dict` method, the `course_key` is passed as a parameter. However, internally, the user model tries to access `course_id` in [this line](https://github.com/openedx/edx-platform/blob/d1854d00200a836fb9f4ba6e8492d147dad1039b/openedx/core/djangoapps/django_comment_common/comment_client/user.py#L237):

```python
course_id = retrieve_params.get('course_id')
```

This causes `course_id` to be `None`, which raises an `InvalidKeyError` from the forum, preventing the user from being created.

**Comment by BryanttV** [comment]
Hi everyone,

This is the issue in edx-platform related to the error reported here: https://github.com/openedx/edx-platform/issues/36793

After identifying the problem, I created a PR to fix it in edx-platform: https://github.com/openedx/edx-platform/pull/36788. Although it’s a small change, it affected other parts of the codebase. Currently, two tests are failing, so it needs to be reviewed carefully to understand why that’s happening.

At the moment, I can’t dedicate more time to this, but I’m documenting it here in case someone else can continue working on the resolution.

**Comment by mariajgrimaldi** [comment]
@BryanttV, thank you so much! I'm unassigning you from this issue and adding the help wanted label to get community support. Thank you so much for all the help!
